### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by Grimcode** [jhasse/chipmunkpp#4]
What's the latest Chipmunk version supported? I'm trying to build your wrapper using the Chipmunk++ solution on Chipmunk 7.0.0. I'm getting the following build errors.

1>------ Build started: Project: Chipmunk++, Configuration: Debug Win32 ------
vect.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

types.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(root)\chipmunkwrapper\src\chipmunkpp\types.cpp(6): error C2614: 'cp::Layers' : illegal member initialization: 'l' is not a base or member
(root)\chipmunkwrapper\src\chipmunkpp\types.cpp(9): error C2614: 'cp::Layers' : illegal member initialization: 'l' is not a base or member
(root)\chipmunkwrapper\src\chipmunkpp\types.cpp(13): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.cpp(13): fatal error C1903: unable to recover from previous error(s); stopping compilation

space.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(11): error C2027: use of undefined type 'cpSpace'

(root)\chipmunk2d\include\chipmunk\chipmunk.h(121) : see declaration of 'cpSpace'

(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(11): error C2227: left of '->staticBody' must point to class/struct/union/generic type
(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(78): error C2061: syntax error : identifier 'cpLayers'
(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(84): error C2061: syntax error : identifier 'cpLayers'
(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(86): error C2039: 't' : is not a member of 'cpSegmentQueryInfo'

(root)\chipmunk2d\include\chipmunk\cpshape.h(40) : see declaration of 'cpSegmentQueryInfo'

(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(87): error C2039: 'n' : is not a member of 'cpSegmentQueryInfo'

(root)\chipmunk2d\include\chipmunk\cpshape.h(40) : see declaration of 'cpSegmentQueryInfo'

(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(89): error C3536: 'rtn': cannot be used before it is initialized
(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(89): error C2664: 'std::shared_ptr<cp::Shape> cp::Space::findPtr(cpShape *) const' : cannot convert argument 1 from 'int' to 'cpShape *'
Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(93): error C2061: syntax error : identifier 'cpLayers'
(root)\chipmunkwrapper\src\chipmunkpp\space.cpp(128): error C2660: 'cpSpaceAddCollisionHandler' : function does not take 8 arguments

shape.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(root)\chipmunkwrapper\src\chipmunkpp\shape.cpp(17): error C2660: 'cpShapePointQuery' : function does not take 2 arguments
(root)\chipmunkwrapper\src\chipmunkpp\shape.cpp(22): error C2660: 'cpShapeSegmentQuery' : function does not take 4 arguments
(root)\chipmunkwrapper\src\chipmunkpp\shape.cpp(24): error C2039: 't' : is not a member of 'cpSegmentQueryInfo'

(root)\chipmunk2d\include\chipmunk\cpshape.h(40) : see declaration of 'cpSegmentQueryInfo'

(root)\chipmunkwrapper\src\chipmunkpp\shape.cpp(25): error C2039: 'n' : is not a member of 'cpSegmentQueryInfo'

(root)\chipmunk2d\include\chipmunk\cpshape.h(40) : see declaration of 'cpSegmentQueryInfo'

(root)\chipmunkwrapper\src\chipmunkpp\shape.cpp(39): error C3861: 'cpShapeSetGroup': identifier not found
(root)\chipmunkwrapper\src\chipmunkpp\shape.cpp(51): error C2061: syntax error : identifier 'cpLayers'
(root)\chipmunkwrapper\src\chipmunkpp\shape.cpp(55): fatal error C1903: unable to recover from previous error(s); stopping compilation

segmentshape.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

polyshape.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(root)\chipmunkwrapper\src\chipmunkpp\polyshape.cpp(7): error C2660: 'cpPolyShapeNew' : function does not take 4 arguments
(root)\chipmunkwrapper\src\chipmunkpp\polyshape.cpp(7): error C2664: 'cp::Shape::Shape(cpShape *,std::shared_ptr<cp::Body>)' : cannot convert argument 1 from 'std::shared_ptr<cp::Body>' to 'const cp::Shape &'
Reason: cannot convert from 'std::shared_ptr<cp::Body>' to 'const cp::Shape'
No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
(root)\chipmunkwrapper\src\chipmunkpp\polyshape.cpp(11): error C3861: 'cpPolyShapeGetNumVerts': identifier not found

circleshape.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

body.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(root)\chipmunkwrapper\src\chipmunkpp\body.cpp(26): error C3861: 'cpBodySetPos': identifier not found
(root)\chipmunkwrapper\src\chipmunkpp\body.cpp(30): error C3861: 'cpBodyGetPos': identifier not found
(root)\chipmunkwrapper\src\chipmunkpp\body.cpp(34): error C3861: 'cpBodyGetVel': identifier not found
(root)\chipmunkwrapper\src\chipmunkpp\body.cpp(38): error C3861: 'cpBodySetVel': identifier not found
(root)\chipmunkwrapper\src\chipmunkpp\body.cpp(42): error C3861: 'cpBodyGetVelLimit': identifier not found
(root)\chipmunkwrapper\src\chipmunkpp\body.cpp(46): error C3861: 'cpBodySetVelLimit': identifier not found

bb.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

arbiter.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

chipmunk.cpp
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2833: 'operator cpLayers' is not a recognized operator or type
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2059: syntax error : 'newline'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(19): error C2238: unexpected token(s) preceding ';'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C2146: syntax error : missing ';' before identifier 'l'
(root)\chipmunkwrapper\src\chipmunkpp\types.hpp(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(root)\chipmunkwrapper\src\chipmunk.cpp(10): error C2660: 'cpAreaForPoly' : function does not take 2 arguments

**Comment by jhasse** [comment]
No, unfortunately I haven't ported it yet to Chipmunk 7.

Is there a "what has changed" or a porting guide for Chipmunk 6 to 7 somewhere? It seems cpLayers was removed/renamed for examples.

**Comment by Grimcode** [comment]
Sorry I'm not familiar with Chipmunk at all. I was going to give it a try but your C++ bindings were the only one still active.

**Comment by jhasse** [comment]
I will keep this open until I've got it fixed for chipmunk 7 ;)

**Comment by jhasse** [comment]
I've ported Chipmunk++ to Chipmunk 7 with fbe676b578375084463bac0e044a05cd81192c4f :)
A lot of things aren't working yet, feel free to open a new issue if you happen run into any problem.

**Comment by Grimcode** [comment]
Builds fine now, thank you for still working on this project.
